runtime: python310  # Choose the Python version that matches your app
service: production-foodhaks
instance_class: F4_1G  # Adjust this based on your needs and traffic

entrypoint: gunicorn -c gunicorn.conf.py -b :$PORT app:app  # Using gunicorn config file for better control

env_variables:
  ENV: 'production'

  # API Key
  OPENAI_API_KEY: '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'


# OpenSearch Credentials
  OPENSEARCH_USER: 'admin'
  OPENSEARCH_PWD: 'Sur8=bn6Z;`QYk!?:gcj54v#fD'
  OPENSEARCH_HOST: 'https://search-foodhak-prod-core-cevlo673wzb5jaa3dcnfalohxe.eu-west-2.es.amazonaws.com'


# API Key
  API_KEY: 'viJ8u142.NaQl7JEW5u8bEJpqnnRuvilTfDbHyWty'
# Optional if VPC connector is needed
vpc_access_connector:
  name: projects/central-muse-388319/locations/us-central1/connectors/vpc-access-connector

automatic_scaling:
  target_cpu_utilization: 0.65  # Increase threshold slightly for better performance under load
  min_instances: 7  # Keep a minimum of 5 instances to reduce cold starts
  max_instances: 20  # Increase the max number of instances to handle more traffic

# Health check settings (optional but recommended)
health_check:
  enable_health_check: true
  check_interval_sec: 10
  timeout_sec: 4
  healthy_threshold: 2
  unhealthy_threshold: 3
  restart_threshold: 60

# Increase request timeout if needed (default is 60 seconds)
handlers:
- url: /.*
  script: auto
  secure: always